### ISSUE TITLE
Hardcoded strings in English

### ISSUE THREAD

**Issue by dinism** [dbnschools/moodle-enrol_easy#5]
Thanks for the plugin.
I'm a PT-PT translator.
Is it possible translate this strings?
![imagem](https://user-images.githubusercontent.com/14828021/101516936-048adc00-3978-11eb-94b0-5ae51cbdd991.png)

**Comment by dbnschools** [comment]
If they are hardcoded I will get it fixed today.

**Comment by dbnschools** [comment]
Fixed in version 1.7.1 which is now published on Github and will be shortly on Moodle.org

**Comment by dinism** [comment]
Thanks a LOT!
